name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu‑latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      # 1. 先安装pnpm，这一步不能省略
      - name: Setup pnpm
        uses: pnpm/action‑setup@v4
        with:
          version: 9

      # 2. setup‑node，cache设置为 pnpm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup‑node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'  # ⚠️这里不能写npm

      # 3. pnpm严格模式安装，替代npm ci
      - run: pnpm install --frozen‑lockfile
      - run: pnpm run build --if‑present
      - run: pnpm test
